name = "calificaciones"
description = ""
version = "0.1.0-dev"

authors = ["Fernando"]
maintainers = ["Fernando <fergonzaramos@yahoo.es>"]
maintainers-logins = ["fgonzalezr1998"]
licenses = "MIT OR Apache-2.0 WITH LLVM-exception"
website = ""
tags = []

executables = ["calificaciones"]
